name: freebsd
on:
  push:
    branches: [main]
    paths:
    - '.github/workflows/freebsd.yaml'
    - 'CMakeLists.txt'
    - 'config.h.in'
    - 'pam_*.c'
    - 'cmake/**'
    - 'include/*'
    - 'pam_modutil/**'
  pull_request:
    # branches: [main]
    paths: 
    - '.github/workflows/freebsd.yaml'
    - 'CMakeLists.txt'
    - 'config.h.in'
    - 'pam_*.c'
    - 'cmake/**'
    - 'include/*'
    - 'pam_modutil/**'
concurrency:
  group: freebsd-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  freebsd-vm:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v3
    - name: build
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        usesh: true
        prepare: pkg install -y cmake
        run: |
          pwd
          arch
          mkdir build && cd build
          cmake .. \
              -DPAM_INSTALL_PREFIX="$(pwd)/installroot"
          cmake --build . -j 2
    - name: test_install
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        usesh: true
        run: |
          pwd
          cd build
          make install
    
    - name: test_uninstall
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        usesh: true
        run: |
          pwd
          cd build
          make uninstall